[package]
name = "tokers"
description = "TikTok mobile (aweme) and web API client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time", "sync"] }
wreq.workspace = true
wreq-util.workspace = true
form_urlencoded.workspace = true
log.workspace = true
flate2.workspace = true
rand.workspace = true
regex.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
